#!/bin/sh

rsync -rav --delete -e 'ssh -i ./.digital-ocean' \
	--exclude '.*' \
	--exclude node_modules \
	. 'root@transport.rest:~/vbb-rest/'

ssh -i ./.digital-ocean 'root@transport.rest' "\
cd ~/vbb-rest
npm i
export NODE_ENV=production
forever stop vbb-rest
forever start -a --uid vbb-rest index.js"
