/agencies?…
/agencies/VBB
/stations?…
/stations/9009101
/stations/9009101/departures
/stations/autocomplete?query=…
/lines?…
/lines/1173
/trips?…
/trips/1
/schedules?…
/schedules/1
/locations?query=…
/routes/9009101/9009102
